// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(markdown_coreFFI)
import markdown_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_markdown_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_markdown_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MarkdownDocumentProtocol : AnyObject {
    
    /**
     * The current document text (owned clone).
     */
    func currentText()  -> String
    
    /**
     * Apply an edit (byte offset, bytes to delete, text to insert).
     */
    func edit(offset: UInt64, delete: UInt64, insert: String) 
    
    /**
     * Whether the source file began with a UTF-8 BOM (re-emitted on save).
     */
    func hasUtf8Bom()  -> Bool
    
    /**
     * Write the document to disk, re-emitting the original BOM if present.
     */
    func saveFile(path: String) throws 
    
}

open class MarkdownDocument:
    MarkdownDocumentProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_markdown_core_fn_clone_markdowndocument(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_markdown_core_fn_free_markdowndocument(pointer, $0) }
    }

    
    /**
     * Construct from raw file bytes (the iOS `UIDocument` load path).
     */
public static func fromBytes(bytes: Data)throws  -> MarkdownDocument {
    return try  FfiConverterTypeMarkdownDocument.lift(try rustCallWithError(FfiConverterTypeEncodingError.lift) {
    uniffi_markdown_core_fn_constructor_markdowndocument_from_bytes(
        FfiConverterData.lower(bytes),$0
    )
})
}
    
    /**
     * New in-memory document from a string.
     */
public static func fromContent(content: String) -> MarkdownDocument {
    return try!  FfiConverterTypeMarkdownDocument.lift(try! rustCall() {
    uniffi_markdown_core_fn_constructor_markdowndocument_from_content(
        FfiConverterString.lower(content),$0
    )
})
}
    
    /**
     * Open a file (BOM/encoding detected and preserved; UTF-16/invalid rejected).
     */
public static func openFile(path: String)throws  -> MarkdownDocument {
    return try  FfiConverterTypeMarkdownDocument.lift(try rustCallWithError(FfiConverterTypeEncodingError.lift) {
    uniffi_markdown_core_fn_constructor_markdowndocument_open_file(
        FfiConverterString.lower(path),$0
    )
})
}
    

    
    /**
     * The current document text (owned clone).
     */
open func currentText() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_markdown_core_fn_method_markdowndocument_current_text(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Apply an edit (byte offset, bytes to delete, text to insert).
     */
open func edit(offset: UInt64, delete: UInt64, insert: String) {try! rustCall() {
    uniffi_markdown_core_fn_method_markdowndocument_edit(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(offset),
        FfiConverterUInt64.lower(delete),
        FfiConverterString.lower(insert),$0
    )
}
}
    
    /**
     * Whether the source file began with a UTF-8 BOM (re-emitted on save).
     */
open func hasUtf8Bom() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_markdown_core_fn_method_markdowndocument_has_utf8_bom(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Write the document to disk, re-emitting the original BOM if present.
     */
open func saveFile(path: String)throws  {try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_markdown_core_fn_method_markdowndocument_save_file(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMarkdownDocument: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MarkdownDocument

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MarkdownDocument {
        return MarkdownDocument(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MarkdownDocument) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MarkdownDocument {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MarkdownDocument, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownDocument_lift(_ pointer: UnsafeMutableRawPointer) throws -> MarkdownDocument {
    return try FfiConverterTypeMarkdownDocument.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMarkdownDocument_lower(_ value: MarkdownDocument) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMarkdownDocument.lower(value)
}


/**
 * Owned, recursive mirror of `ast::SyntaxNode`. The frontend walks this to
 * render read mode / WYSIWYM without a live tree-sitter tree.
 */
public struct AstNode {
    public var kind: NodeKind
    public var span: Span
    public var start: Position
    public var end: Position
    public var children: [AstNode]
    public var text: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: NodeKind, span: Span, start: Position, end: Position, children: [AstNode], text: String?) {
        self.kind = kind
        self.span = span
        self.start = start
        self.end = end
        self.children = children
        self.text = text
    }
}



extension AstNode: Equatable, Hashable {
    public static func ==(lhs: AstNode, rhs: AstNode) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.span != rhs.span {
            return false
        }
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        if lhs.children != rhs.children {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(span)
        hasher.combine(start)
        hasher.combine(end)
        hasher.combine(children)
        hasher.combine(text)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAstNode: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AstNode {
        return
            try AstNode(
                kind: FfiConverterTypeNodeKind.read(from: &buf), 
                span: FfiConverterTypeSpan.read(from: &buf), 
                start: FfiConverterTypePosition.read(from: &buf), 
                end: FfiConverterTypePosition.read(from: &buf), 
                children: FfiConverterSequenceTypeAstNode.read(from: &buf), 
                text: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: AstNode, into buf: inout [UInt8]) {
        FfiConverterTypeNodeKind.write(value.kind, into: &buf)
        FfiConverterTypeSpan.write(value.span, into: &buf)
        FfiConverterTypePosition.write(value.start, into: &buf)
        FfiConverterTypePosition.write(value.end, into: &buf)
        FfiConverterSequenceTypeAstNode.write(value.children, into: &buf)
        FfiConverterOptionString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAstNode_lift(_ buf: RustBuffer) throws -> AstNode {
    return try FfiConverterTypeAstNode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAstNode_lower(_ value: AstNode) -> RustBuffer {
    return FfiConverterTypeAstNode.lower(value)
}


public struct Backlink {
    public var path: String
    public var line: UInt64
    public var context: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, line: UInt64, context: String) {
        self.path = path
        self.line = line
        self.context = context
    }
}



extension Backlink: Equatable, Hashable {
    public static func ==(lhs: Backlink, rhs: Backlink) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.line != rhs.line {
            return false
        }
        if lhs.context != rhs.context {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(line)
        hasher.combine(context)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBacklink: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Backlink {
        return
            try Backlink(
                path: FfiConverterString.read(from: &buf), 
                line: FfiConverterUInt64.read(from: &buf), 
                context: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Backlink, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterUInt64.write(value.line, into: &buf)
        FfiConverterString.write(value.context, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBacklink_lift(_ buf: RustBuffer) throws -> Backlink {
    return try FfiConverterTypeBacklink.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBacklink_lower(_ value: Backlink) -> RustBuffer {
    return FfiConverterTypeBacklink.lower(value)
}


public struct Diagnostic {
    public var span: Span
    public var severity: Severity
    public var rule: String
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(span: Span, severity: Severity, rule: String, message: String) {
        self.span = span
        self.severity = severity
        self.rule = rule
        self.message = message
    }
}



extension Diagnostic: Equatable, Hashable {
    public static func ==(lhs: Diagnostic, rhs: Diagnostic) -> Bool {
        if lhs.span != rhs.span {
            return false
        }
        if lhs.severity != rhs.severity {
            return false
        }
        if lhs.rule != rhs.rule {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(span)
        hasher.combine(severity)
        hasher.combine(rule)
        hasher.combine(message)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDiagnostic: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Diagnostic {
        return
            try Diagnostic(
                span: FfiConverterTypeSpan.read(from: &buf), 
                severity: FfiConverterTypeSeverity.read(from: &buf), 
                rule: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Diagnostic, into buf: inout [UInt8]) {
        FfiConverterTypeSpan.write(value.span, into: &buf)
        FfiConverterTypeSeverity.write(value.severity, into: &buf)
        FfiConverterString.write(value.rule, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnostic_lift(_ buf: RustBuffer) throws -> Diagnostic {
    return try FfiConverterTypeDiagnostic.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDiagnostic_lower(_ value: Diagnostic) -> RustBuffer {
    return FfiConverterTypeDiagnostic.lower(value)
}


/**
 * A detected math region (byte offsets into the source). FEAT-038.
 */
public struct MathSpan {
    public var start: UInt64
    public var end: UInt64
    public var display: Bool
    public var latex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt64, end: UInt64, display: Bool, latex: String) {
        self.start = start
        self.end = end
        self.display = display
        self.latex = latex
    }
}



extension MathSpan: Equatable, Hashable {
    public static func ==(lhs: MathSpan, rhs: MathSpan) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        if lhs.display != rhs.display {
            return false
        }
        if lhs.latex != rhs.latex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
        hasher.combine(display)
        hasher.combine(latex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMathSpan: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MathSpan {
        return
            try MathSpan(
                start: FfiConverterUInt64.read(from: &buf), 
                end: FfiConverterUInt64.read(from: &buf), 
                display: FfiConverterBool.read(from: &buf), 
                latex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MathSpan, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.start, into: &buf)
        FfiConverterUInt64.write(value.end, into: &buf)
        FfiConverterBool.write(value.display, into: &buf)
        FfiConverterString.write(value.latex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMathSpan_lift(_ buf: RustBuffer) throws -> MathSpan {
    return try FfiConverterTypeMathSpan.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMathSpan_lower(_ value: MathSpan) -> RustBuffer {
    return FfiConverterTypeMathSpan.lower(value)
}


public struct Mutation {
    public var offset: UInt64
    public var delete: UInt64
    public var insert: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(offset: UInt64, delete: UInt64, insert: String) {
        self.offset = offset
        self.delete = delete
        self.insert = insert
    }
}



extension Mutation: Equatable, Hashable {
    public static func ==(lhs: Mutation, rhs: Mutation) -> Bool {
        if lhs.offset != rhs.offset {
            return false
        }
        if lhs.delete != rhs.delete {
            return false
        }
        if lhs.insert != rhs.insert {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(offset)
        hasher.combine(delete)
        hasher.combine(insert)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMutation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mutation {
        return
            try Mutation(
                offset: FfiConverterUInt64.read(from: &buf), 
                delete: FfiConverterUInt64.read(from: &buf), 
                insert: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Mutation, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.offset, into: &buf)
        FfiConverterUInt64.write(value.delete, into: &buf)
        FfiConverterString.write(value.insert, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMutation_lift(_ buf: RustBuffer) throws -> Mutation {
    return try FfiConverterTypeMutation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMutation_lower(_ value: Mutation) -> RustBuffer {
    return FfiConverterTypeMutation.lower(value)
}


/**
 * 0-based row/column position.
 */
public struct Position {
    public var row: UInt64
    public var column: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(row: UInt64, column: UInt64) {
        self.row = row
        self.column = column
    }
}



extension Position: Equatable, Hashable {
    public static func ==(lhs: Position, rhs: Position) -> Bool {
        if lhs.row != rhs.row {
            return false
        }
        if lhs.column != rhs.column {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(row)
        hasher.combine(column)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePosition: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Position {
        return
            try Position(
                row: FfiConverterUInt64.read(from: &buf), 
                column: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Position, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.row, into: &buf)
        FfiConverterUInt64.write(value.column, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePosition_lift(_ buf: RustBuffer) throws -> Position {
    return try FfiConverterTypePosition.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePosition_lower(_ value: Position) -> RustBuffer {
    return FfiConverterTypePosition.lower(value)
}


/**
 * Byte-offset range into the source text.
 */
public struct Span {
    public var start: UInt64
    public var end: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt64, end: UInt64) {
        self.start = start
        self.end = end
    }
}



extension Span: Equatable, Hashable {
    public static func ==(lhs: Span, rhs: Span) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSpan: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Span {
        return
            try Span(
                start: FfiConverterUInt64.read(from: &buf), 
                end: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Span, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.start, into: &buf)
        FfiConverterUInt64.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpan_lift(_ buf: RustBuffer) throws -> Span {
    return try FfiConverterTypeSpan.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSpan_lower(_ value: Span) -> RustBuffer {
    return FfiConverterTypeSpan.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CheckboxState {
    
    case checked
    case unchecked
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCheckboxState: FfiConverterRustBuffer {
    typealias SwiftType = CheckboxState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CheckboxState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .checked
        
        case 2: return .unchecked
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CheckboxState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .checked:
            writeInt(&buf, Int32(1))
        
        
        case .unchecked:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckboxState_lift(_ buf: RustBuffer) throws -> CheckboxState {
    return try FfiConverterTypeCheckboxState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCheckboxState_lower(_ value: CheckboxState) -> RustBuffer {
    return FfiConverterTypeCheckboxState.lower(value)
}



extension CheckboxState: Equatable, Hashable {}




/**
 * General engine failure surfaced to Swift.
 */
public enum CoreError {

    
    
    case Io(msg: String
    )
    case Wikilink(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Wikilink(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Io(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .Wikilink(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension CoreError: Equatable, Hashable {}

extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}


/**
 * Open/decode failure — mirrors `crate::EncodingError`.
 */
public enum EncodingError {

    
    
    case Utf16Le
    case Utf16Be
    case InvalidUtf8
    case Io(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncodingError: FfiConverterRustBuffer {
    typealias SwiftType = EncodingError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncodingError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Utf16Le
        case 2: return .Utf16Be
        case 3: return .InvalidUtf8
        case 4: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EncodingError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .Utf16Le:
            writeInt(&buf, Int32(1))
        
        
        case .Utf16Be:
            writeInt(&buf, Int32(2))
        
        
        case .InvalidUtf8:
            writeInt(&buf, Int32(3))
        
        
        case let .Io(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension EncodingError: Equatable, Hashable {}

extension EncodingError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Owned mirror of `ast::NodeKind` (Strings cloned; no borrows cross the FFI).
 */

public enum NodeKind {
    
    case document
    case heading(level: UInt8
    )
    case paragraph
    case blockQuote
    case orderedList
    case unorderedList
    case listItem(checkbox: CheckboxState?
    )
    case fencedCodeBlock(language: String?
    )
    case indentedCodeBlock
    case htmlBlock
    case thematicBreak
    case frontMatter
    case table
    case tableHead
    case tableRow
    case tableCell
    case tableDelimiterRow
    case text
    case emphasis
    case strong
    case strikethrough
    case inlineCode
    case link(destination: String?
    )
    case image(source: String?
    )
    case autolink
    case inlineHtml
    case lineBreak
    case softBreak
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNodeKind: FfiConverterRustBuffer {
    typealias SwiftType = NodeKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NodeKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .document
        
        case 2: return .heading(level: try FfiConverterUInt8.read(from: &buf)
        )
        
        case 3: return .paragraph
        
        case 4: return .blockQuote
        
        case 5: return .orderedList
        
        case 6: return .unorderedList
        
        case 7: return .listItem(checkbox: try FfiConverterOptionTypeCheckboxState.read(from: &buf)
        )
        
        case 8: return .fencedCodeBlock(language: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 9: return .indentedCodeBlock
        
        case 10: return .htmlBlock
        
        case 11: return .thematicBreak
        
        case 12: return .frontMatter
        
        case 13: return .table
        
        case 14: return .tableHead
        
        case 15: return .tableRow
        
        case 16: return .tableCell
        
        case 17: return .tableDelimiterRow
        
        case 18: return .text
        
        case 19: return .emphasis
        
        case 20: return .strong
        
        case 21: return .strikethrough
        
        case 22: return .inlineCode
        
        case 23: return .link(destination: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 24: return .image(source: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 25: return .autolink
        
        case 26: return .inlineHtml
        
        case 27: return .lineBreak
        
        case 28: return .softBreak
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NodeKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .document:
            writeInt(&buf, Int32(1))
        
        
        case let .heading(level):
            writeInt(&buf, Int32(2))
            FfiConverterUInt8.write(level, into: &buf)
            
        
        case .paragraph:
            writeInt(&buf, Int32(3))
        
        
        case .blockQuote:
            writeInt(&buf, Int32(4))
        
        
        case .orderedList:
            writeInt(&buf, Int32(5))
        
        
        case .unorderedList:
            writeInt(&buf, Int32(6))
        
        
        case let .listItem(checkbox):
            writeInt(&buf, Int32(7))
            FfiConverterOptionTypeCheckboxState.write(checkbox, into: &buf)
            
        
        case let .fencedCodeBlock(language):
            writeInt(&buf, Int32(8))
            FfiConverterOptionString.write(language, into: &buf)
            
        
        case .indentedCodeBlock:
            writeInt(&buf, Int32(9))
        
        
        case .htmlBlock:
            writeInt(&buf, Int32(10))
        
        
        case .thematicBreak:
            writeInt(&buf, Int32(11))
        
        
        case .frontMatter:
            writeInt(&buf, Int32(12))
        
        
        case .table:
            writeInt(&buf, Int32(13))
        
        
        case .tableHead:
            writeInt(&buf, Int32(14))
        
        
        case .tableRow:
            writeInt(&buf, Int32(15))
        
        
        case .tableCell:
            writeInt(&buf, Int32(16))
        
        
        case .tableDelimiterRow:
            writeInt(&buf, Int32(17))
        
        
        case .text:
            writeInt(&buf, Int32(18))
        
        
        case .emphasis:
            writeInt(&buf, Int32(19))
        
        
        case .strong:
            writeInt(&buf, Int32(20))
        
        
        case .strikethrough:
            writeInt(&buf, Int32(21))
        
        
        case .inlineCode:
            writeInt(&buf, Int32(22))
        
        
        case let .link(destination):
            writeInt(&buf, Int32(23))
            FfiConverterOptionString.write(destination, into: &buf)
            
        
        case let .image(source):
            writeInt(&buf, Int32(24))
            FfiConverterOptionString.write(source, into: &buf)
            
        
        case .autolink:
            writeInt(&buf, Int32(25))
        
        
        case .inlineHtml:
            writeInt(&buf, Int32(26))
        
        
        case .lineBreak:
            writeInt(&buf, Int32(27))
        
        
        case .softBreak:
            writeInt(&buf, Int32(28))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNodeKind_lift(_ buf: RustBuffer) throws -> NodeKind {
    return try FfiConverterTypeNodeKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNodeKind_lower(_ value: NodeKind) -> RustBuffer {
    return FfiConverterTypeNodeKind.lower(value)
}



extension NodeKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Severity {
    
    case error
    case warning
    case hint
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSeverity: FfiConverterRustBuffer {
    typealias SwiftType = Severity

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Severity {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .error
        
        case 2: return .warning
        
        case 3: return .hint
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Severity, into buf: inout [UInt8]) {
        switch value {
        
        
        case .error:
            writeInt(&buf, Int32(1))
        
        
        case .warning:
            writeInt(&buf, Int32(2))
        
        
        case .hint:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeverity_lift(_ buf: RustBuffer) throws -> Severity {
    return try FfiConverterTypeSeverity.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeverity_lower(_ value: Severity) -> RustBuffer {
    return FfiConverterTypeSeverity.lower(value)
}



extension Severity: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeCheckboxState: FfiConverterRustBuffer {
    typealias SwiftType = CheckboxState?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeCheckboxState.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeCheckboxState.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAstNode: FfiConverterRustBuffer {
    typealias SwiftType = [AstNode]

    public static func write(_ value: [AstNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAstNode.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AstNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [AstNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAstNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeBacklink: FfiConverterRustBuffer {
    typealias SwiftType = [Backlink]

    public static func write(_ value: [Backlink], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeBacklink.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Backlink] {
        let len: Int32 = try readInt(&buf)
        var seq = [Backlink]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeBacklink.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDiagnostic: FfiConverterRustBuffer {
    typealias SwiftType = [Diagnostic]

    public static func write(_ value: [Diagnostic], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDiagnostic.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Diagnostic] {
        let len: Int32 = try readInt(&buf)
        var seq = [Diagnostic]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDiagnostic.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMathSpan: FfiConverterRustBuffer {
    typealias SwiftType = [MathSpan]

    public static func write(_ value: [MathSpan], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMathSpan.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MathSpan] {
        let len: Int32 = try readInt(&buf)
        var seq = [MathSpan]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMathSpan.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMutation: FfiConverterRustBuffer {
    typealias SwiftType = [Mutation]

    public static func write(_ value: [Mutation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMutation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Mutation] {
        let len: Int32 = try readInt(&buf)
        var seq = [Mutation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMutation.read(from: &buf))
        }
        return seq
    }
}
/**
 * Apply formatter mutations to `text` and return the result. Mutations are
 * applied offset-descending so earlier offsets stay valid; out-of-range or
 * non-char-boundary mutations are skipped rather than panicking.
 */
public func applyMutations(text: String, mutations: [Mutation]) -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_apply_mutations(
        FfiConverterString.lower(text),
        FfiConverterSequenceTypeMutation.lower(mutations),$0
    )
})
}
/**
 * Find every `.md` file that links to `file_path`.
 */
public func backlinks(filePath: String)throws  -> [Backlink] {
    return try  FfiConverterSequenceTypeBacklink.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_markdown_core_fn_func_backlinks(
        FfiConverterString.lower(filePath),$0
    )
})
}
/**
 * Create a new `.md` file for a wikilink target that doesn't exist yet.
 */
public func createWikilinkTarget(linkText: String, currentFilePath: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_markdown_core_fn_func_create_wikilink_target(
        FfiConverterString.lower(linkText),
        FfiConverterString.lower(currentFilePath),$0
    )
})
}
/**
 * Parse + run the document doctor (no filesystem context).
 */
public func diagnose(text: String) -> [Diagnostic] {
    return try!  FfiConverterSequenceTypeDiagnostic.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_diagnose(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Parse + run the doctor WITH filesystem context (enables the broken-link rule).
 */
public func diagnoseWithContext(text: String, docPath: String, siblings: [String]) -> [Diagnostic] {
    return try!  FfiConverterSequenceTypeDiagnostic.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_diagnose_with_context(
        FfiConverterString.lower(text),
        FfiConverterString.lower(docPath),
        FfiConverterSequenceString.lower(siblings),$0
    )
})
}
/**
 * Parse + run the formatter, returning the mutations to apply.
 */
public func format(text: String) -> [Mutation] {
    return try!  FfiConverterSequenceTypeMutation.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_format(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Find the `$…$` / `$$…$$` math regions in `text` (rendering is the frontend's
 * job — SwiftMath on Apple, KaTeX on web).
 */
public func mathSpans(text: String) -> [MathSpan] {
    return try!  FfiConverterSequenceTypeMathSpan.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_math_spans(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Parse markdown into the typed AST root.
 */
public func parse(text: String) -> AstNode {
    return try!  FfiConverterTypeAstNode.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_parse(
        FfiConverterString.lower(text),$0
    )
})
}
/**
 * Resolve a `[[wikilink]]` target against the filesystem near `current_file_path`.
 */
public func resolveWikilink(linkText: String, currentFilePath: String) -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_markdown_core_fn_func_resolve_wikilink(
        FfiConverterString.lower(linkText),
        FfiConverterString.lower(currentFilePath),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_markdown_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_markdown_core_checksum_func_apply_mutations() != 44428) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_backlinks() != 17020) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_create_wikilink_target() != 31026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_diagnose() != 27352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_diagnose_with_context() != 25032) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_format() != 60704) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_math_spans() != 59175) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_parse() != 24317) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_func_resolve_wikilink() != 35610) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_method_markdowndocument_current_text() != 11080) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_method_markdowndocument_edit() != 31971) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_method_markdowndocument_has_utf8_bom() != 44052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_method_markdowndocument_save_file() != 23149) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_constructor_markdowndocument_from_bytes() != 41669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_constructor_markdowndocument_from_content() != 56488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_markdown_core_checksum_constructor_markdowndocument_open_file() != 64589) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all